### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by agwatts** [conveyal/gtfs-editor#157] opened 2015-02-12 19:09 UTC
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~       javax.media->jai_core 1.1.3: missing artifact
~       voldemort.store.compress->h2-lzf 1.0
~       java3d->vecmath 1.3.2

Suggestions where I might find these?

**Comment by mattwigway** [comment] 2015-02-12 20:52
The application should work anyhow. I need to figure out where that message is coming from---it doesn't actually need those dependencies.

**Comment by agwatts** [comment] 2015-02-12 20:53
It did when I tried it again. The first time, I got a compilation exception. 

play.exceptions.CompilationException: org.hibernatespatial.readers.Feature cannot be resolved
        at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
        at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
        at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
        at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
        at play.Play.start(Play.java:516)
        at play.Play.detectChanges(Play.java:630)
        at play.Invoker$Invocation.init(Invoker.java:198)
        at Invocation.HTTP Request(Play!)

**Comment by mattwigway** [comment] 2015-02-12 20:57
Hmm, is the file hibernate-spatial-1.1.1.jar in the lib/ directory (this is an unmanaged dependency, checked into the repo rather than retrieved through maven)? That is where that class is contained.

**Comment by agwatts** [comment] 2015-02-12 20:59
It is. Now I've got a null pointer exception.

NullPointerException occured : Try to read admin on null object models.Account (controllers.Application.initSession, line 65)

play.exceptions.JavaExecutionException: Try to read admin on null object models.Account (controllers.Application.initSession, line 65)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
        at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException: Try to read admin on null object models.Account (controllers.Application.initSession, line 65)
        at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:213)
        at controllers.Application.initSession(Application.java:65)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:510)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
        at play.mvc.ActionInvoker.handleBefores(ActionInvoker.java:328)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:142)
        ... 1 more

Thoughts on that?

**Comment by mattwigway** [comment] 2015-02-12 21:09
Hmm. I've seen that in the past when I still have cookies from an old installation active. Try clearing cookies for the host your app is running on?

Regarding the dependency issue, these seem to be dependencies of play itself, and thus the issue is difficult to resolve. We'll migrate to play 2 eventually and that should solve it; until then we can just ignore the message.

**Comment by agwatts** [comment] 2015-02-12 21:23
Great. Thanks.

**Comment by mattwigway** [comment] 2015-02-13 19:27
Reopening this since we haven't actually fixed the dependency problem.

**Comment by markjd84** [comment] 2015-02-17 16:43
+1 for this problem, but `wget`ing the three jars from the repo seems to have fixed it. (0.2.1)

**Comment by mattwigway** [comment] 2015-03-02 16:21
I think this should be fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with). Feel free to reopen if it isn't.

**Closed by mattwigway** 2015-03-02 16:21 UTC

**Comment by bindmisson** [comment] 2015-04-06 17:49
WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~       javax.media->jai_core 1.1.3: missing artifact
~       voldemort.store.compress->h2-lzf 1.0
~       java3d->vecmath 1.3.2
~       jgridshift->jgridshift 1.0


Cant import GTFS..


Show Below error

Execution exception
OutOfMemoryError occured : Java heap space

In /app/jobs/ProcessGtfsSnapshotMerge.java (around line 110)

106:
         // map from (non-gtfs) agency IDs to transactions.
107:
         Map<String, AgencyTx> agencyTxs = Maps.newHashMap();
108:
         
109:
         try {
110:
        		input = GTFSFeed.fromFile(gtfsFile.getAbsolutePath());
111:
     		
112:
         	Logger.info("GtfsImporter: importing agencies...");        
113:
         	// store agencies
114:
         	for (com.conveyal.gtfs.model.Agency gtfsAgency : input.agency.values()) {
115:
    	       		Agency agency = new Agency(gtfsAgency);
116:
         		// don't save the agency until we've come up with the stop centroid, below.

**Comment by mattwigway** [comment] 2015-04-08 14:10
@bindmisson, the warnings about missing dependencies are unrelated - it looks like the issue is that you're running out of memory. Try increasing the memory allocation in application.conf. Thanks for your interest in the tool!

**Comment by bindmisson** [comment] 2015-04-08 17:20
Hello,

I'm new to GTFS

Can you Show me the Lines to add in to the /root/gtfs-editor/conf/application.conf



-  Vishnu
