### ISSUE TITLE
Error when storing route due to publiclyVisible element

### ISSUE THREAD

**Issue by skibu** [conveyal/gtfs-editor#214] opened 2015-04-16 19:18 UTC
When I create a route and try to save it I get an error message on the website. When I look at the output of the application I see the stack trace shown below. My guess is that while publiclyVisible is defined on the web page it is not part of class models.transit.Route . This means that with the current code (I tried pulling the latest greatest today 4/16/2015) one cannot store a route.

The stack trace:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "publiclyVisible" (class models.transit.Route), not marked as ignorable (13 known properties: "agencyId", "routeUrl", "wheelchairBoarding", "gtfsRouteId", "routeTextColor", "routeLongName", "status", "comments", "routeDesc", "routeColor", "id", "routeShortName", "routeTypeId" [truncated]])
 at [Source: {"id":"34da8cd8-8aaa-41b6-9b4d-908bc0a41868","gtfsRouteId":"ROUTE_34da8cd8-8aaa-41b6-9b4d-908bc0a41868","routeShortName":"shuttle","routeLongName":"AeroCentre Shuttle","routeDesc":"","routeTypeId":"0af28c70-9bf5-4f4c-9b85-517caf06f692","routeUrl":"","routeColor":"","routeTextColor":"","comments":"Initial test route","status":"IN_PROGRESS","agencyId":"9b46ae27-57f7-48d0-96b3-8d4c39d1b8e0","wheelchairBoarding":"UNKNOWN","publiclyVisible":false}; line: 1, column: 446] (through reference chain: Route["publiclyVisible"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:731)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:915)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1276)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:243)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2146)
        at controllers.api.RouteController.updateRoute(RouteController.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:251)
        at play.Invoker$Invocation.run(Invoker.java:278)
        at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:229)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mattwigway** [comment] 2015-06-09 15:29
Ah oops, thanks for the report. This element was intended to be removed and was from the API but not the UI - fixed by #226.

**Closed by mattwigway** 2015-06-09 15:29 UTC
