### ISSUE TITLE
"NoSuchFieldError: HTTP_URI_OGC" When creating an alignment

### ISSUE THREAD

**Issue by medwards** [conveyal/gtfs-editor#176] opened 2015-02-17 12:04 UTC
Added a sequence of stops by hand to the map, added them to a new pattern (did not enter any travel time or dwell information, I was going to use calculate times for this), click "Create Alignment" and the geometry appears but the follow stacktrace is produced:

```
@6l861phbd
Internal Server Error (500) for request PUT /api/trippattern/42

Execution exception (In /app/utils/GeoUtils.java around line 81)
NoSuchFieldError occured : HTTP_URI_OGC

play.exceptions.JavaExecutionException: HTTP_URI_OGC
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NoSuchFieldError: HTTP_URI_OGC
	at org.geotools.referencing.factory.HTTP_URI_AuthorityFactory.getAuthority(HTTP_URI_AuthorityFactory.java:77)
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.createFallbacks(ManyAuthoritiesFactory.java:167)
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.<init>(ManyAuthoritiesFactory.java:125)
	at org.geotools.referencing.DefaultAuthorityFactory.getBackingFactory(DefaultAuthorityFactory.java:116)
	at org.geotools.referencing.DefaultAuthorityFactory.<init>(DefaultAuthorityFactory.java:69)
	at org.geotools.referencing.CRS.getAuthorityFactory(CRS.java:251)
	at utils.GeoUtils.getTransform(GeoUtils.java:81)
	at controllers.Api.updateTripPattern(Api.java:581)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
```

**Comment by dgoujard** [comment] 2015-02-17 13:07
Check my ticket #169 same issue and maybe same solution

**Comment by medwards** [comment] 2015-02-17 13:20
Ah, thanks for the tip, I did this:
```
rm libs/*
./play-1.2.5/play dependencies
wget --directory-prefix=libs http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
wget --directory-prefix=libs http://dev.mapfish.org/maven/repository/voldemort/store/compress/h2-lzf/1.0/h2-lzf-1.0.jar
wget --directory-prefix=libs http://download.osgeo.org/webdav/geotools/java3d/vecmath/1.3.2/vecmath-1.3.2.jar
# these dependencies are in the repository and play dependencies don't restore them
git checkout lib/hibernate-spatial-1.1.1.jar
git checkout lib/hibernate-spatial-postgis-1.1.1.jar
git checkout lib/postgis-2.0.0SVN.jar
```

I still get the same error. I'm going to wipe the database ( :'( ) and see if that helps.

**Comment by dgoujard** [comment] 2015-02-17 13:22
I tested my installation instructions on Ubuntu 14.10 64bit with success :/

**Comment by medwards** [comment] 2015-02-17 13:24
How did you configure your database? I did `CREATE EXTENSION postgis` and `postgis_topology`

**Comment by dgoujard** [comment] 2015-02-17 13:27
```
sudo su postgres
createdb gtfs-editor

psql gtfs-editor < /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
```
But ```CREATE EXTENSION postgis``` is the same i think.

What version of java have you installed? I tried Oracle Java 8 but it's didn't work, i currently use OpenJDK 7

**Comment by medwards** [comment] 2015-02-17 13:35
OpenJDK 7, but I'm running on PosgreSQL 9.3. (Ubuntu 14.04 btw)

Trying to reproduce with a fresh database but now postgis isn't being installed properly. Lawl. I'll try to get more feedback soon.

**Comment by dgoujard** [comment] 2015-02-17 13:38
The path for the postgis.sql depend of you postgis version and postgresql version.
I use packaged postgresql and postgresql-postgis it's more simple to get an VM ready for gtfs-editor.

**Comment by medwards** [comment] 2015-02-17 13:48
Wiped everything as best I could and I still get the Exception. Can you identify the postgis packages you installed?
```
medwards@jesuit:~/forks/pnt/libs$ dpkg --get-selections postgis
postgis						install
```
(from the stock Ubuntu repo)

**Comment by dgoujard** [comment] 2015-02-17 13:51
openjdk-7-jre:amd64				install
openjdk-7-jre-headless:amd64			install
postgis						install
postgis-doc					install
postgresql					install
postgresql-9.4					install
postgresql-9.4-postgis-2.1			install
postgresql-9.4-postgis-scripts			install
postgresql-client				install
postgresql-client-9.4				install
postgresql-client-common			install
postgresql-common				install
postgresql-contrib				install
postgresql-contrib-9.4				install
postgresql-doc					install
postgresql-doc-9.4				install

**Comment by medwards** [comment] 2015-02-17 13:53
Tried to do `sudo -u postgres psql gtfs-editor < /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql` and got `postgis is already installed` so if it is a postgis problem it's going to be pretty quirky.

If we verify having the same postgis problems then I'm going to go back to assuming its some wonky jar file stuff, here is what I get from `select PostGIS_full_version();`  
`POSTGIS="2.1.2 r12389" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1, released 2013/08/26" LIBXML="2.9.1" LIBJSON="UNKNOWN" RASTER`

**Comment by medwards** [comment] 2015-02-17 13:55
This is my dependencies output, could you please run yours again and I can compare?
```
medwards@jesuit:~/forks/conveyal-gtfs-editor$ ./play-1.2.5/play dependencies
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.2.5, http://www.playframework.org
~
~ Resolving dependencies using /home/medwards/forks/conveyal-gtfs-editor/conf/dependencies.yml,
~
~ 	com.typesafe.akka->akka-actor 2.0.3 (from typesafe)
~ 	org.scala-lang->scala-library 2.9.2 (from mavenCentral)
~ 	com.typesafe->config 0.3.1 (from mavenCentral)
~ 	com.typesafe.akka->akka-remote 2.0.3 (from typesafe)
~ 	io.netty->netty 3.5.3.Final (from mavenCentral)
~ 	com.google.protobuf->protobuf-java 2.4.1 (from mavenCentral)
~ 	net.debasishg->sjson_2.9.1 0.15 (from mavenCentral)
~ 	net.databinder->dispatch-json_2.9.1 0.8.5 (from mavenCentral)
~ 	org.apache.httpcomponents->httpclient 4.1 (from mavenCentral)
~ 	org.apache.httpcomponents->httpcore 4.1 (from mavenCentral)
~ 	org.objenesis->objenesis 1.2 (from mavenCentral)
~ 	gov.sandia.foundry->gov-sandia-cognition-common-core 3.3.2 (from mavenCentral)
~ 	com.googlecode.matrix-toolkits-java->mtj 0.9.14 (from mavenCentral)
~ 	com.googlecode.netlib-java->netlib-java 0.9.3 (from mavenCentral)
~ 	net.sourceforge.f2j->arpack_combined_all 0.1 (from mavenCentral)
~ 	gov.sandia.foundry->gov-sandia-cognition-learning-core 3.3.2 (from mavenCentral)
~ 	com.google.guava->guava 11.0.1 (from mavenCentral)
~ 	com.google.code.findbugs->jsr305 1.3.9 (from mavenCentral)
~ 	com.google.guava->guava-bootstrap 11.0.1 (from mavenCentral)
~ 	com.vividsolutions->jts 1.12 (from mavenCentral)
~ 	xerces->xercesImpl 2.4.0 (from mavenCentral)
~ 	org.geotools->gt-main 8.0-M4 (from osgeo)
~ 	org.geotools->gt-api 8.0-M4 (from osgeo)
~ 	org.geotools->gt-referencing 8.0-M4 (from osgeo)
~ 	commons-pool->commons-pool 1.5.4 (from mavenCentral)
~ 	org.geotools->gt-metadata 8.0-M4 (from osgeo)
~ 	org.geotools->gt-opengis 8.0-M4 (from osgeo)
~ 	net.java.dev.jsr-275->jsr-275 1.0-beta-2 (from mavenCentral)
~ 	javax.media->jai_core 1.1.3 (from mavenCentral)
~ 	jdom->jdom 1.0 (from mavenCentral)
~ 	org.geotools->gt-geojson 8.0-M4 (from osgeo)
~ 	com.googlecode.json-simple->json-simple 1.1 (from mavenCentral)
~ 	org.codehaus.jackson->jackson-core-asl 1.9.5 (from mavenCentral)
~ 	org.codehaus.jackson->jackson-mapper-asl 1.9.5 (from mavenCentral)
~ 	org.opentripplanner->otp 1.0.0-SNAPSHOT (from conveyal)
~ 	javax.servlet->servlet-api 2.5 (from mavenCentral)
~ 	net.sf.opencsv->opencsv 2.0 (from mavenCentral)
~
~ Some dependencies have been evicted,
~
~	xstream 1.3.1 is overriden by xstream 1.4.2
~	commons-io 1.4 is overriden by commons-io 2.0.1
~	scala-library 2.9.1 is overriden by scala-library 2.9.2
~	junit 4.4 is overriden by junit 4.10
~
~ WARNING: Some dependencies could not be downloaded (use --verbose for details),
~
~	javax.media->jai_core 1.1.3: missing artifact
~
~ Installing resolved dependencies,
~
~ 	lib/akka-actor-2.0.3.jar
~ 	lib/akka-remote-2.0.3.jar
~ 	lib/gov-sandia-cognition-common-core-3.3.2.jar
~ 	lib/gov-sandia-cognition-learning-core-3.3.2.jar
~ 	lib/guava-11.0.1.jar
~ 	lib/jts-1.12.jar
~ 	lib/gt-main-8.0-M4.jar
~ 	lib/gt-geojson-8.0-M4.jar
~ 	lib/jackson-core-asl-1.9.5.jar
~ 	lib/jackson-mapper-asl-1.9.5.jar
~ 	lib/otp-1.0.0-SNAPSHOT.jar
~ 	lib/opencsv-2.0.jar
~ 	lib/scala-library-2.9.2.jar
~ 	lib/config-0.3.1.jar
~ 	lib/netty-3.5.3.Final.jar
~ 	lib/protobuf-java-2.4.1.jar
~ 	lib/sjson_2.9.1-0.15.jar
~ 	lib/dispatch-json_2.9.1-0.8.5.jar
~ 	lib/objenesis-1.2.jar
~ 	lib/httpclient-4.1.jar
~ 	lib/httpcore-4.1.jar
~ 	lib/mtj-0.9.14.jar
~ 	lib/netlib-java-0.9.3.jar
~ 	lib/arpack_combined_all-0.1.jar
~ 	lib/jsr305-1.3.9.jar
~ 	lib/guava-bootstrap-11.0.1.jar
~ 	lib/xercesImpl-2.4.0.jar
~ 	lib/gt-api-8.0-M4.jar
~ 	lib/jdom-1.0.jar
~ 	lib/gt-referencing-8.0-M4.jar
~ 	lib/commons-pool-1.5.4.jar
~ 	lib/gt-metadata-8.0-M4.jar
~ 	lib/gt-opengis-8.0-M4.jar
~ 	lib/jsr-275-1.0-beta-2.jar
~ 	lib/json-simple-1.1.jar
~ 	lib/servlet-api-2.5.jar
~
~ *****************************************************************************
~ WARNING: Your lib/ and modules/ directories and not synced with current dependencies (use --sync to automatically delete them)
~
~ 	Unknown: /home/medwards/forks/conveyal-gtfs-editor/lib/h2-lzf-1.0.jar
~ 	Unknown: /home/medwards/forks/conveyal-gtfs-editor/lib/vecmath-1.3.2.jar
~ 	Unknown: /home/medwards/forks/conveyal-gtfs-editor/lib/hibernate-spatial-postgis-1.1.1.jar
~ 	Unknown: /home/medwards/forks/conveyal-gtfs-editor/lib/postgis-2.0.0SVN.jar
~ 	Unknown: /home/medwards/forks/conveyal-gtfs-editor/lib/jai_core-1.1.3.jar
~ 	Unknown: /home/medwards/forks/conveyal-gtfs-editor/lib/hibernate-spatial-1.1.1.jar
~ *****************************************************************************
~
~ *****************************************************************************
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~	javax.media->jai_core 1.1.3: missing artifact
~	voldemort.store.compress->h2-lzf 1.0
~	java3d->vecmath 1.3.2
~ *****************************************************************************
~
~ Some dependencies are still missing.
```

**Comment by dgoujard** [comment] 2015-02-17 13:57
```
root@ubuntu-gtfseditor:/home/damien/gtfs-editor# ../play-1.2.5/play dependencies
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.2.5, http://www.playframework.org
~
~ Resolving dependencies using /home/damien/gtfs-editor/conf/dependencies.yml,
~
~ 	com.typesafe.akka->akka-actor 2.0.3 (from typesafe)
~ 	org.scala-lang->scala-library 2.9.2 (from mavenCentral)
~ 	com.typesafe->config 0.3.1 (from mavenCentral)
~ 	com.typesafe.akka->akka-remote 2.0.3 (from typesafe)
~ 	io.netty->netty 3.5.3.Final (from mavenCentral)
~ 	com.google.protobuf->protobuf-java 2.4.1 (from mavenCentral)
~ 	net.debasishg->sjson_2.9.1 0.15 (from mavenCentral)
~ 	net.databinder->dispatch-json_2.9.1 0.8.5 (from mavenCentral)
~ 	org.apache.httpcomponents->httpclient 4.1 (from mavenCentral)
~ 	org.apache.httpcomponents->httpcore 4.1 (from mavenCentral)
~ 	org.objenesis->objenesis 1.2 (from mavenCentral)
~ 	gov.sandia.foundry->gov-sandia-cognition-common-core 3.3.2 (from mavenCentral)
~ 	com.googlecode.matrix-toolkits-java->mtj 0.9.14 (from mavenCentral)
~ 	com.googlecode.netlib-java->netlib-java 0.9.3 (from mavenCentral)
~ 	net.sourceforge.f2j->arpack_combined_all 0.1 (from mavenCentral)
~ 	gov.sandia.foundry->gov-sandia-cognition-learning-core 3.3.2 (from mavenCentral)
~ 	com.google.guava->guava 11.0.1 (from mavenCentral)
~ 	com.google.code.findbugs->jsr305 1.3.9 (from mavenCentral)
~ 	com.google.guava->guava-bootstrap 11.0.1 (from mavenCentral)
~ 	com.vividsolutions->jts 1.12 (from mavenCentral)
~ 	xerces->xercesImpl 2.4.0 (from mavenCentral)
~ 	org.geotools->gt-main 8.0-M4 (from osgeo)
~ 	org.geotools->gt-api 8.0-M4 (from osgeo)
~ 	org.geotools->gt-referencing 8.0-M4 (from osgeo)
~ 	commons-pool->commons-pool 1.5.4 (from mavenCentral)
~ 	org.geotools->gt-metadata 8.0-M4 (from osgeo)
~ 	org.geotools->gt-opengis 8.0-M4 (from osgeo)
~ 	net.java.dev.jsr-275->jsr-275 1.0-beta-2 (from mavenCentral)
~ 	javax.media->jai_core 1.1.3 (from mavenCentral)
~ 	jdom->jdom 1.0 (from mavenCentral)
~ 	org.geotools->gt-geojson 8.0-M4 (from osgeo)
~ 	com.googlecode.json-simple->json-simple 1.1 (from mavenCentral)
~ 	org.codehaus.jackson->jackson-core-asl 1.9.5 (from mavenCentral)
~ 	org.codehaus.jackson->jackson-mapper-asl 1.9.5 (from mavenCentral)
~ 	org.opentripplanner->otp 1.0.0-SNAPSHOT (from conveyal)
~ 	javax.servlet->servlet-api 2.5 (from mavenCentral)
~ 	net.sf.opencsv->opencsv 2.0 (from mavenCentral)
~
~ Some dependencies have been evicted,
~
~	xstream 1.3.1 is overriden by xstream 1.4.2
~	commons-io 1.4 is overriden by commons-io 2.0.1
~	scala-library 2.9.1 is overriden by scala-library 2.9.2
~	junit 4.4 is overriden by junit 4.10
~
~ WARNING: Some dependencies could not be downloaded (use --verbose for details),
~
~	javax.media->jai_core 1.1.3: missing artifact
~
~ Installing resolved dependencies,
~
~ 	lib/akka-actor-2.0.3.jar
~ 	lib/akka-remote-2.0.3.jar
~ 	lib/gov-sandia-cognition-common-core-3.3.2.jar
~ 	lib/gov-sandia-cognition-learning-core-3.3.2.jar
~ 	lib/guava-11.0.1.jar
~ 	lib/jts-1.12.jar
~ 	lib/gt-main-8.0-M4.jar
~ 	lib/gt-geojson-8.0-M4.jar
~ 	lib/jackson-core-asl-1.9.5.jar
~ 	lib/jackson-mapper-asl-1.9.5.jar
~ 	lib/otp-1.0.0-SNAPSHOT.jar
~ 	lib/opencsv-2.0.jar
~ 	lib/scala-library-2.9.2.jar
~ 	lib/config-0.3.1.jar
~ 	lib/netty-3.5.3.Final.jar
~ 	lib/protobuf-java-2.4.1.jar
~ 	lib/sjson_2.9.1-0.15.jar
~ 	lib/dispatch-json_2.9.1-0.8.5.jar
~ 	lib/objenesis-1.2.jar
~ 	lib/httpclient-4.1.jar
~ 	lib/httpcore-4.1.jar
~ 	lib/mtj-0.9.14.jar
~ 	lib/netlib-java-0.9.3.jar
~ 	lib/arpack_combined_all-0.1.jar
~ 	lib/jsr305-1.3.9.jar
~ 	lib/guava-bootstrap-11.0.1.jar
~ 	lib/xercesImpl-2.4.0.jar
~ 	lib/gt-api-8.0-M4.jar
~ 	lib/jdom-1.0.jar
~ 	lib/gt-referencing-8.0-M4.jar
~ 	lib/commons-pool-1.5.4.jar
~ 	lib/gt-metadata-8.0-M4.jar
~ 	lib/gt-opengis-8.0-M4.jar
~ 	lib/jsr-275-1.0-beta-2.jar
~ 	lib/json-simple-1.1.jar
~ 	lib/servlet-api-2.5.jar
~
~ *****************************************************************************
~ WARNING: Your lib/ and modules/ directories and not synced with current dependencies (use --sync to automatically delete them)
~
~ 	Unknown: /home/damien/gtfs-editor/lib/hibernate-spatial-postgis-1.1.1.jar
~ 	Unknown: /home/damien/gtfs-editor/lib/hibernate-spatial-1.1.1.jar
~ 	Unknown: /home/damien/gtfs-editor/lib/h2-lzf-1.0.jar
~ 	Unknown: /home/damien/gtfs-editor/lib/postgis-2.0.0SVN.jar
~ 	Unknown: /home/damien/gtfs-editor/lib/vecmath-1.3.2.jar
~ 	Unknown: /home/damien/gtfs-editor/lib/jai_core-1.1.3.jar
~ *****************************************************************************
~
~ *****************************************************************************
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~	javax.media->jai_core 1.1.3: missing artifact
~	voldemort.store.compress->h2-lzf 1.0
~	java3d->vecmath 1.3.2
~ *****************************************************************************
~
~ Some dependencies are still missing.
~
```
```
root@ubuntu-gtfseditor:/home/damien/gtfs-editor# ls lib/
akka-actor-2.0.3.jar                          jackson-core-asl-1.9.5.jar
akka-remote-2.0.3.jar                         jackson-mapper-asl-1.9.5.jar
arpack_combined_all-0.1.jar                   jai_core-1.1.3.jar
commons-pool-1.5.4.jar                        jdom-1.0.jar
config-0.3.1.jar                              json-simple-1.1.jar
dispatch-json_2.9.1-0.8.5.jar                 jsr-275-1.0-beta-2.jar
gov-sandia-cognition-common-core-3.3.2.jar    jsr305-1.3.9.jar
gov-sandia-cognition-learning-core-3.3.2.jar  jts-1.12.jar
gt-api-8.0-M4.jar                             mtj-0.9.14.jar
gt-geojson-8.0-M4.jar                         netlib-java-0.9.3.jar
gt-main-8.0-M4.jar                            netty-3.5.3.Final.jar
gt-metadata-8.0-M4.jar                        objenesis-1.2.jar
gt-opengis-8.0-M4.jar                         opencsv-2.0.jar
gt-referencing-8.0-M4.jar                     otp-1.0.0-SNAPSHOT.jar
guava-11.0.1.jar                              postgis-2.0.0SVN.jar
guava-bootstrap-11.0.1.jar                    protobuf-java-2.4.1.jar
h2-lzf-1.0.jar                                scala-library-2.9.2.jar
hibernate-spatial-1.1.1.jar                   servlet-api-2.5.jar
hibernate-spatial-postgis-1.1.1.jar           sjson_2.9.1-0.15.jar
httpclient-4.1.jar                            vecmath-1.3.2.jar
httpcore-4.1.jar                              xercesImpl-2.4.0.jar
```

**Comment by medwards** [comment] 2015-02-17 13:59
Jar files are the same
*pulls hair out*

**Comment by dgoujard** [comment] 2015-02-17 14:00
I didn't know what to do for your problem :/ i got the same and with clean install and wget for missing jar it's worked...

**Comment by medwards** [comment] 2015-02-17 14:06
I'm stumped too. Do you think the `HTTP_URI_AuthorityFactory` is doing something crazy like doing an HTTP lookup with the URI? Then maybe its just a firewall issue locally?

**Comment by dgoujard** [comment] 2015-02-17 14:08
I think it's more likely an jar stuff issue because i already exactly the same issue and i resolved many weird problem with jar downloads. But you have the same setup as me...

**Comment by medwards** [comment] 2015-02-17 14:12
Aight, lets get dirty:
```
medwards@jesuit:~/forks/conveyal-gtfs-editor$ md5sum lib/gt-referencing-8.0-M4.jar 
ea50911736be38705b5e8ca8c39cffae  lib/gt-referencing-8.0-M4.jar
```

**Comment by dgoujard** [comment] 2015-02-17 14:14
9a433ee3477452eed46241434e1d3741  akka-actor-2.0.3.jar
873b73e091b924b2b16bb18ea4a0f010  akka-remote-2.0.3.jar
83d82dd480da2aeba6429e746453ec0b  arpack_combined_all-0.1.jar
80e9d1cbd70542f4f293793d109679a9  commons-pool-1.5.4.jar
3a253c4076cbe892028365ba9fb1d451  config-0.3.1.jar
e49a8f7072b111c38558b7a902d079a1  dispatch-json_2.9.1-0.8.5.jar
0ab91c1df2ab3d8eff20d63a266536d0  gov-sandia-cognition-common-core-3.3.2.jar
9b4bde8fdcab6947597bf65214898e16  gov-sandia-cognition-learning-core-3.3.2.jar
9b886d762755142281e30aa22f5a2bd2  gt-api-8.0-M4.jar
734f28717c28f39256ebf1f2ff4f8682  gt-geojson-8.0-M4.jar
3ad34c9f5250dc81036029c4a17eb5da  gt-main-8.0-M4.jar
43dc87e6d344504ed067faeb39a9e0b4  gt-metadata-8.0-M4.jar
574cf4768271d3ea29e8f70efc81858e  gt-opengis-8.0-M4.jar
ea50911736be38705b5e8ca8c39cffae  gt-referencing-8.0-M4.jar
69a3d06554ebc3027c9432509a67ede2  guava-11.0.1.jar
63a29daca38cd59a948e3b55ca3a7763  guava-bootstrap-11.0.1.jar
007c2ac9b133a555cdd6bbd7a3a0c46a  h2-lzf-1.0.jar
350d8d5620c870d0d9753df96919b869  hibernate-spatial-1.1.1.jar
6be407db0a1ff185533388933ac26937  hibernate-spatial-postgis-1.1.1.jar
241e32c3115c3d3d2bfde8345e763a56  httpclient-4.1.jar
db31aa554da6b48e36351001fc6c6d14  httpcore-4.1.jar
bc60754518a8a820859e87b44a560496  jackson-core-asl-1.9.5.jar
6b51578abe1729336a6a737894e111d2  jackson-mapper-asl-1.9.5.jar
f398bc038307ee434bac1b93ba3ab02d  jai_core-1.1.3.jar
0b8f97de82fc9529b1028a77125ce4f8  jdom-1.0.jar
eb342044fc56be9ba49fbfc9789f1bb5  json-simple-1.1.jar
bcc6ce452a9806054d6ecd0cc2b14d36  jsr-275-1.0-beta-2.jar
1d5a772e400b04bb67a7ef4a0e0996d8  jsr305-1.3.9.jar
fc76020355ecd77fcf32b0c49cb55616  jts-1.12.jar
0494b05d5f5c4c1a83505d1846757695  mtj-0.9.14.jar
dc52c266056aa8ab05a8abed663588dc  netlib-java-0.9.3.jar
ebe8d5caee8206c6c2e1f759934e6108  netty-3.5.3.Final.jar
bee117291d50b41b8e8cf0ac5435df1d  objenesis-1.2.jar
2524a73bcfd45a54b97a37b98289fc8b  opencsv-2.0.jar
44184eba9dcb43e276921e80872a92e8  otp-1.0.0-SNAPSHOT.jar
26b3a7136f226c01e657c2cefcb82643  postgis-2.0.0SVN.jar
1253f05305eed82f6aae1d8c8aad43da  protobuf-java-2.4.1.jar
2a4b4c5b1d9a1a92e52fd0751a5d1b6a  scala-library-2.9.2.jar
69ca51af4e9a67a1027a7f95b52c3e8f  servlet-api-2.5.jar
fd6f1fa9914a2b517c63358ad8e702d3  sjson_2.9.1-0.15.jar
7e32027bb4f69680ca5005f74a230ab0  vecmath-1.3.2.jar
454f0042d31547561a9c9031402d6b73  xercesImpl-2.4.0.jar

**Comment by medwards** [comment] 2015-02-17 14:17
They all match... hookayy... gonna get someone else to try this too to make sure its not a ghost in the machine.

**Comment by medwards** [comment] 2015-02-17 14:59
Was able to repro on a fresh 14.04 machine. Dunno what else I'm missing at this stage..

**Comment by dgoujard** [comment] 2015-02-17 15:58
You right i can reproduce this bug on an VPS with Ubuntu 14.04 64bit

**Comment by medwards** [comment] 2015-02-17 16:06
Maybe the difference is in `/tmp/Geotools`? Alternatively maybe you have an hsqldb driver on your classpath that isn't part of the play dependencies, so its never accessed?

**Comment by dgoujard** [comment] 2015-02-17 16:10
I just tried with another VPS on digital ocean with the same error. I didn't understand i downloaded Ubuntu Iso 14.10 64 bits and create a local VM and it's work... Same ubuntu version, same commands line and different results... I will try to create another local vm...

**Comment by medwards** [comment] 2015-02-17 16:15
I suspect it has something to do with /tmp/Geotools and HSQLDB/EPSG dependencies. The only material I could find on this bug said "You need and epsg jar" and one of them was a jar that would open a hsql db in a temporary folder. Looking at your working machine, I'd doublecheck the classpath and see what other java libraries might be in your install of openjdk. Maybe in 14.10 they added some libraries that aren't in the 14.04 package

**Comment by dgoujard** [comment] 2015-02-17 16:44
```
damien@ubuntu-gtfseditor:~$ ls /tmp/Geotools/Databases/HSQL/v7.9.0/
EPSG_creation_marker.txt  EPSG.data  EPSG.properties  EPSG.script
```

I install a new Ubuntu VM 14.10 with VirtualBox and i can create alignment... I didn't understand the difference between and digital ocean ubuntu 14.10 and my local ubuntu 14.10.

What is your vm provider?

**Comment by medwards** [comment] 2015-02-17 16:59
They're just stock Ubuntu installs. Can you list the jars distributed with your 14.10 jdk?

-----Original Message-----

**Comment by dgoujard** [comment] 2015-02-17 17:00
Where can i found this jar (i'm not an java expert)

**Comment by medwards** [comment] 2015-02-17 17:44
Probably somewhere in /usr/lib/jvm/java-7-openjdk-amd64 (you can also do
update-alternatives --config java to see). I think there is a lib folder
but I forget off the top of my head and not at a computer where I can check.

**Comment by medwards** [comment] 2015-02-18 07:34
`/usr/lib/jvm/java-7-openjdk-amd64/lib` and `/usr/lib/jvm/java-7-openjdk-amd64/jre/lib` have jars. Also do you get any results with `dpkg --get-selections hsql`?

**Comment by dgoujard** [comment] 2015-02-18 07:51
```
damien@ubuntu-gtfseditor:~$ ls /usr/lib/jvm/java-7-openjdk-amd64/lib
ls: impossible d'accéder à /usr/lib/jvm/java-7-openjdk-amd64/lib: Aucun fichier ou dossier de ce type
damien@ubuntu-gtfseditor:~$ ls /usr/lib/jvm/java-7-openjdk-amd64/
bin/  docs/ jre/  man/  
damien@ubuntu-gtfseditor:~$ ls /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/
accessibility.properties  images                psfontj2d.properties
amd64                     jar.binfmt            psfont.properties.ja
calendars.properties      javazic.jar           resources.jar
charsets.jar              jce.jar               rhino.jar
classlist                 jexec                 rt.jar
cmm                       jsse.jar              security
compilefontconfig.jar     jvm.hprof.txt         sound.properties
content-types.properties  logging.properties    swing.properties
currency.data             management            tz.properties
ext                       management-agent.jar  zi
flavormap.properties      meta-index
fontconfig.properties     net.properties
damien@ubuntu-gtfseditor:~$ dpkg --get-selections hsql
dpkg: aucun paquet ne correspond à hsql
damien@ubuntu-gtfseditor:~$ 
```

I exported my working VirtualBox VM on an harddrive and at noon i will host the OVA on my NAS (i have an fiber connexion), so you can download it and try to understand the difference between your setup and my setup.

**Comment by medwards** [comment] 2015-02-18 07:54
Cool, I'll probably be able to take a look next week.

**Comment by markjd84** [comment] 2015-02-18 09:24
+1 for me too, I've followed all the instructions in here and #169 but I still get 

```
Execution exception (In /app/utils/GeoUtils.java around line 81)
NoSuchFieldError occured : HTTP_URI_OGC
```

Am going to see if there is anything I can do to fix this morning & will update if any progress.

**Comment by markjd84** [comment] 2015-02-18 10:40
Tried a few fairly heavy-handed and unintelligent dumps of different JARs into the `lib/` folder from `geotools-8.0.bin.zip`. Had no reason to think that might work but worth a try. It didn't work anyway.

**Comment by dgoujard** [comment] 2015-02-18 12:19
Here my OVA file : http://gofile.me/27P7X/yymjoffZ Or https://mega.co.nz/#!C8o3TZIT!grcnFyjlAha9b1VkXHh1oVvST5-HIcDi3ARzRyY7OHc

ssh login : damien
ssh password : password

GTFSEditor Login : test
GTFSEditor password : test

**Comment by medwards** [comment] 2015-02-18 21:20
I enjoy how a lot of this issue is just random stuff that we're hoping is the problem ^^

Welcome to the issue mark 😊 

-----Original Message-----

**Comment by dgoujard** [comment] 2015-02-19 15:31
I didn't know if it's related but what is your version of postgresql? My working vm 14.10 as 9.4 package but show 
```
postgres@ubuntu-gtfseditor:~$ psql --version
psql (PostgreSQL) 9.4beta3
```
My other VM with trouble, with the same Ubuntu version and same package name return
```
postgres@testgtfs:~$ psql --version
psql (PostgreSQL) 9.4.1
 ```

**Comment by markjd84** [comment] 2015-02-19 15:50
Yes this looks to be related: 

Ubuntu 12.04
PostGres 9.1.14
PostGIS 1.5

on the machine where it wasn't working. However, still can't export GTFS (see #168) so will update there if any progress with that.

**Comment by dgoujard** [comment] 2015-02-19 15:54
@medwards I think i found a solution for this error (HTTP_URI_OGC), i download geotools-12.2 and 
remplace geotools-M4 jar files by this new one.
```
wget "http://downloads.sourceforge.net/project/geotools/GeoTools%2012%20Releases/12.2/geotools-12.2-bin.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fgeotools%2Ffiles%2FGeoTools%252012%2520Releases%2F12.2%2F&ts=1424360473&use_mirror=switch"
unzip thefile
cd geotools-12.2/
rm ../gtfs-editor/lib/gt-
cp gt-api-12.2.jar gt-geojson-12.2.jar gt-main-12.2.jar gt-metadata-12.2.jar gt-opengis-12.2.jar gt-referencing-12.2.jar ../gtfs-editor/lib
```

Still ```OutOfMemoryError occured : Java heap space``` when i export only one line but it may be ram related, i will try with more ram on my VPS.

**Comment by mattwigway** [comment] 2015-02-19 16:05
@dgoujard haven't really tested in ram-constrained environments (I have 16GB), but it should work. Are you using 0.2.1? The export code used to use the OneBusAway GTFS exporter which holds an entire GTFS feed in RAM; now it uses the Conveyal GTFS exporter which uses a disk-backed scratch file to generate the feed.

**Comment by dgoujard** [comment] 2015-02-19 16:10
@mattwigway I'm using current master branch, tested with 4Go of Ram and the same issue, but with the same code with my local vm and the same amount of Ram work. 
It's not ram related.

I try to understand why it's work with VM but not on digital ocean with more or less same ubuntu version. I'm not the only one with install/export issues.

**Comment by markjd84** [comment] 2015-02-19 16:20
Just to confirm, the installation I have is from @dgoujard (thanks!) and running branch `0.2.1.1-gac3cd06`

It all works great, and I no longer get the `NoSuchFieldError` above, but my export still only produces one route out of 120.... (!)

Cheers for continued help guys.

**Comment by dgoujard** [comment] 2015-02-19 16:21
@markjd84 i upgraded my cloud ocean server Ram to 4Go and still have the issue** but with 8go** of Ram it work (with just one line). I think there are some Ram management issue. Try to upgrade with more Ram you VM.

**Comment by mattwigway** [comment] 2015-02-19 16:40
Yeah it shouldn't take that much ram. I'm rewriting the entire backend right now (see #166), so hopefully that will solve this issue.

**Comment by mattwigway** [comment] 2015-03-02 16:19
I think this should be fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with).

**Comment by mattwigway** [comment] 2015-03-02 16:19
Feel free to reopen if it isn't.

**Closed by mattwigway** 2015-03-02 16:19 UTC

**Comment by rq4** [comment] 2016-02-13 01:23
Im using a digitaloceans account with 512 MB and getting the OutofMemory:Java Heap space error. Im new to ubuntu and conveyal. could you explain if its a RAM issue or if I should try to fix the dependencies? if the latter how do i do that?

**Comment by mattwigway** [comment] 2016-02-13 01:28
It's definitely a memory issue, 512mb isn't much.

**Comment by rq4** [comment] 2016-02-13 01:38
How much would you recommend? I get this error when trying to import a gtfs
zip file
