### ISSUE TITLE
Error  The method apply(String) of type new Function<String,ServiceCalendar.ServiceCalendarForPattern>(){} must override a superclass method

### ISSUE THREAD

**Issue by aj07mm** [conveyal/gtfs-editor#208] opened 2015-04-10 22:36 UTC
Listening for transport dt_socket at address: 8000
19:33:10,323 INFO  ~ Starting /Users/aj07mm/Desktop/gtfs-editor
19:33:11,693 WARN  ~ You're running Play! in DEV mode
19:33:11,834 INFO  ~ Listening for HTTP on port 9000 (Waiting a first request to start) ...
19:33:21,558 ERROR ~ 

@6lmnbk2c0
Internal Server Error (500) for request GET /

Compilation error (In /app/controllers/api/CalendarController.java around line 77)
The file /app/controllers/api/CalendarController.java could not be compiled. Error raised is : The method apply(String) of type new Function&lt;String,ServiceCalendar.ServiceCalendarForPattern>(){} must override a superclass method

play.exceptions.CompilationException: The method apply(String) of type new Function<String,ServiceCalendar.ServiceCalendarForPattern>(){} must override a superclass method
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
	at play.Play.start(Play.java:516)
	at play.Play.detectChanges(Play.java:630)
	at play.Invoker$Invocation.init(Invoker.java:198)
	at Invocation.HTTP Request(Play!)

**Comment by mattwigway** [comment] 2015-04-14 21:18
This looks like a dependency issue; perhaps it's picking up an older/newer version of Guava.

**Comment by ustroetz** [comment] 2015-05-27 17:44
same problem here

**Comment by mattwigway** [comment] 2015-06-09 15:30
Duplicate of #195; this is an incompatibility with Java 8 and Guava; Editor works with Java 7.

**Closed by mattwigway** 2015-06-09 15:30 UTC
